// AUTO-GENERATED by scripts/gen-db-types.mjs — do not edit by hand.
// Regenerate after schema changes: node scripts/gen-db-types.mjs

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      attendance: {
        Row: {
          id: string;
          shift_id: string;
          employee_id: string;
          site_id: string | null;
          check_in_at: string | null;
          check_in_loc: string | null;
          check_out_at: string | null;
          check_out_loc: string | null;
          method: Database["public"]["Enums"]["attendance_method"];
          status: Database["public"]["Enums"]["attendance_status"];
          client_ref: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shift_id: string;
          employee_id: string;
          site_id?: string | null;
          check_in_at?: string | null;
          check_in_loc?: string | null;
          check_out_at?: string | null;
          check_out_loc?: string | null;
          method?: Database["public"]["Enums"]["attendance_method"];
          status?: Database["public"]["Enums"]["attendance_status"];
          client_ref?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shift_id?: string;
          employee_id?: string;
          site_id?: string | null;
          check_in_at?: string | null;
          check_in_loc?: string | null;
          check_out_at?: string | null;
          check_out_loc?: string | null;
          method?: Database["public"]["Enums"]["attendance_method"];
          status?: Database["public"]["Enums"]["attendance_status"];
          client_ref?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_log: {
        Row: {
          id: number;
          actor_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          before: Json | null;
          after: Json | null;
          ip: string | null;
          at: string;
        };
        Insert: {
          id?: number;
          actor_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          ip?: string | null;
          at?: string;
        };
        Update: {
          id?: number;
          actor_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          ip?: string | null;
          at?: string;
        };
      };
      checkpoint_scans: {
        Row: {
          id: string;
          session_id: string;
          checkpoint_id: string;
          employee_id: string;
          scanned_at: string;
          location: string | null;
          method: Database["public"]["Enums"]["checkpoint_method"];
          in_geofence: boolean | null;
          client_ref: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          checkpoint_id: string;
          employee_id: string;
          scanned_at?: string;
          location?: string | null;
          method: Database["public"]["Enums"]["checkpoint_method"];
          in_geofence?: boolean | null;
          client_ref?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          checkpoint_id?: string;
          employee_id?: string;
          scanned_at?: string;
          location?: string | null;
          method?: Database["public"]["Enums"]["checkpoint_method"];
          in_geofence?: boolean | null;
          client_ref?: string | null;
          created_at?: string;
        };
      };
      checkpoints: {
        Row: {
          id: string;
          route_id: string;
          name: string;
          seq: number;
          method: Database["public"]["Enums"]["checkpoint_method"];
          location: string | null;
          radius_m: number | null;
          tag_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          route_id: string;
          name: string;
          seq: number;
          method?: Database["public"]["Enums"]["checkpoint_method"];
          location?: string | null;
          radius_m?: number | null;
          tag_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          route_id?: string;
          name?: string;
          seq?: number;
          method?: Database["public"]["Enums"]["checkpoint_method"];
          location?: string | null;
          radius_m?: number | null;
          tag_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      clients: {
        Row: {
          id: string;
          name: string;
          contact_name: string | null;
          contact_phone: string | null;
          contact_email: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          contact_name?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          contact_name?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      conversation_members: {
        Row: {
          conversation_id: string;
          user_id: string;
          joined_at: string;
          last_read_at: string | null;
        };
        Insert: {
          conversation_id: string;
          user_id: string;
          joined_at?: string;
          last_read_at?: string | null;
        };
        Update: {
          conversation_id?: string;
          user_id?: string;
          joined_at?: string;
          last_read_at?: string | null;
        };
      };
      conversations: {
        Row: {
          id: string;
          title: string | null;
          is_group: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title?: string | null;
          is_group?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string | null;
          is_group?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      current_location: {
        Row: {
          employee_id: string;
          shift_id: string | null;
          location: string;
          accuracy_m: number | null;
          speed_mps: number | null;
          heading_deg: number | null;
          battery_pct: number | null;
          is_moving: boolean | null;
          recorded_at: string;
          updated_at: string;
          lng: number | null;
          lat: number | null;
        };
        Insert: {
          employee_id: string;
          shift_id?: string | null;
          location: string;
          accuracy_m?: number | null;
          speed_mps?: number | null;
          heading_deg?: number | null;
          battery_pct?: number | null;
          is_moving?: boolean | null;
          recorded_at: string;
          updated_at?: string;
          lng?: number | null;
          lat?: number | null;
        };
        Update: {
          employee_id?: string;
          shift_id?: string | null;
          location?: string;
          accuracy_m?: number | null;
          speed_mps?: number | null;
          heading_deg?: number | null;
          battery_pct?: number | null;
          is_moving?: boolean | null;
          recorded_at?: string;
          updated_at?: string;
          lng?: number | null;
          lat?: number | null;
        };
      };
      geofence_events: {
        Row: {
          id: string;
          employee_id: string;
          geofence_id: string | null;
          site_id: string | null;
          shift_id: string | null;
          event_type: Database["public"]["Enums"]["geofence_event_type"];
          source: Database["public"]["Enums"]["geofence_event_source"];
          location: string | null;
          occurred_at: string;
          is_expected: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          geofence_id?: string | null;
          site_id?: string | null;
          shift_id?: string | null;
          event_type: Database["public"]["Enums"]["geofence_event_type"];
          source?: Database["public"]["Enums"]["geofence_event_source"];
          location?: string | null;
          occurred_at?: string;
          is_expected?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          geofence_id?: string | null;
          site_id?: string | null;
          shift_id?: string | null;
          event_type?: Database["public"]["Enums"]["geofence_event_type"];
          source?: Database["public"]["Enums"]["geofence_event_source"];
          location?: string | null;
          occurred_at?: string;
          is_expected?: boolean | null;
          created_at?: string;
        };
      };
      geofences: {
        Row: {
          id: string;
          site_id: string | null;
          name: string;
          shape: Database["public"]["Enums"]["geofence_shape"];
          area: string | null;
          center: string | null;
          radius_m: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          site_id?: string | null;
          name: string;
          shape: Database["public"]["Enums"]["geofence_shape"];
          area?: string | null;
          center?: string | null;
          radius_m?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          site_id?: string | null;
          name?: string;
          shape?: Database["public"]["Enums"]["geofence_shape"];
          area?: string | null;
          center?: string | null;
          radius_m?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      incidents: {
        Row: {
          id: string;
          type: Database["public"]["Enums"]["incident_type"];
          status: Database["public"]["Enums"]["incident_status"];
          raised_by: string | null;
          site_id: string | null;
          location: string | null;
          description: string | null;
          acknowledged_by: string | null;
          acknowledged_at: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          resolution_note: string | null;
          client_ref: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          type?: Database["public"]["Enums"]["incident_type"];
          status?: Database["public"]["Enums"]["incident_status"];
          raised_by?: string | null;
          site_id?: string | null;
          location?: string | null;
          description?: string | null;
          acknowledged_by?: string | null;
          acknowledged_at?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          resolution_note?: string | null;
          client_ref?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          type?: Database["public"]["Enums"]["incident_type"];
          status?: Database["public"]["Enums"]["incident_status"];
          raised_by?: string | null;
          site_id?: string | null;
          location?: string | null;
          description?: string | null;
          acknowledged_by?: string | null;
          acknowledged_at?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          resolution_note?: string | null;
          client_ref?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      location_history: {
        Row: {
          employee_id: string;
          bucket_at: string;
          location: string;
        };
        Insert: {
          employee_id: string;
          bucket_at: string;
          location: string;
        };
        Update: {
          employee_id?: string;
          bucket_at?: string;
          location?: string;
        };
      };
      location_pings: {
        Row: {
          id: string;
          employee_id: string;
          shift_id: string | null;
          location: string;
          accuracy_m: number | null;
          speed_mps: number | null;
          heading_deg: number | null;
          battery_pct: number | null;
          is_moving: boolean | null;
          is_mock: boolean;
          recorded_at: string;
          received_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          shift_id?: string | null;
          location: string;
          accuracy_m?: number | null;
          speed_mps?: number | null;
          heading_deg?: number | null;
          battery_pct?: number | null;
          is_moving?: boolean | null;
          is_mock?: boolean;
          recorded_at: string;
          received_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          shift_id?: string | null;
          location?: string;
          accuracy_m?: number | null;
          speed_mps?: number | null;
          heading_deg?: number | null;
          battery_pct?: number | null;
          is_moving?: boolean | null;
          is_mock?: boolean;
          recorded_at?: string;
          received_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string | null;
          body: string | null;
          attachment_url: string | null;
          client_ref: string | null;
          sent_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id?: string | null;
          body?: string | null;
          attachment_url?: string | null;
          client_ref?: string | null;
          sent_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender_id?: string | null;
          body?: string | null;
          attachment_url?: string | null;
          client_ref?: string | null;
          sent_at?: string;
        };
      };
      patrol_routes: {
        Row: {
          id: string;
          name: string;
          site_id: string | null;
          zone_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          site_id?: string | null;
          zone_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          site_id?: string | null;
          zone_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      patrol_sessions: {
        Row: {
          id: string;
          route_id: string;
          employee_id: string;
          shift_id: string | null;
          status: Database["public"]["Enums"]["patrol_status"];
          started_at: string;
          ended_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          route_id: string;
          employee_id: string;
          shift_id?: string | null;
          status?: Database["public"]["Enums"]["patrol_status"];
          started_at?: string;
          ended_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          route_id?: string;
          employee_id?: string;
          shift_id?: string | null;
          status?: Database["public"]["Enums"]["patrol_status"];
          started_at?: string;
          ended_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          full_name: string;
          employee_code: string | null;
          phone: string | null;
          employment_type: Database["public"]["Enums"]["employment_type"];
          status: Database["public"]["Enums"]["employee_status"];
          avatar_url: string | null;
          push_token: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id: string;
          full_name: string;
          employee_code?: string | null;
          phone?: string | null;
          employment_type?: Database["public"]["Enums"]["employment_type"];
          status?: Database["public"]["Enums"]["employee_status"];
          avatar_url?: string | null;
          push_token?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          full_name?: string;
          employee_code?: string | null;
          phone?: string | null;
          employment_type?: Database["public"]["Enums"]["employment_type"];
          status?: Database["public"]["Enums"]["employee_status"];
          avatar_url?: string | null;
          push_token?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      shifts: {
        Row: {
          id: string;
          employee_id: string;
          site_id: string | null;
          zone_id: string | null;
          vehicle_id: string | null;
          status: Database["public"]["Enums"]["shift_status"];
          starts_at: string;
          ends_at: string;
          started_at: string | null;
          ended_at: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          site_id?: string | null;
          zone_id?: string | null;
          vehicle_id?: string | null;
          status?: Database["public"]["Enums"]["shift_status"];
          starts_at: string;
          ends_at: string;
          started_at?: string | null;
          ended_at?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          site_id?: string | null;
          zone_id?: string | null;
          vehicle_id?: string | null;
          status?: Database["public"]["Enums"]["shift_status"];
          starts_at?: string;
          ends_at?: string;
          started_at?: string | null;
          ended_at?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      sites: {
        Row: {
          id: string;
          client_id: string;
          zone_id: string | null;
          name: string;
          code: string | null;
          address: string | null;
          location: string;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          lng: number | null;
          lat: number | null;
        };
        Insert: {
          id?: string;
          client_id: string;
          zone_id?: string | null;
          name: string;
          code?: string | null;
          address?: string | null;
          location: string;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          lng?: number | null;
          lat?: number | null;
        };
        Update: {
          id?: string;
          client_id?: string;
          zone_id?: string | null;
          name?: string;
          code?: string | null;
          address?: string | null;
          location?: string;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          lng?: number | null;
          lat?: number | null;
        };
      };
      task_events: {
        Row: {
          id: string;
          task_id: string;
          actor_id: string | null;
          from_status: Database["public"]["Enums"]["task_status"] | null;
          to_status: Database["public"]["Enums"]["task_status"] | null;
          note: string | null;
          at: string;
        };
        Insert: {
          id?: string;
          task_id: string;
          actor_id?: string | null;
          from_status?: Database["public"]["Enums"]["task_status"] | null;
          to_status?: Database["public"]["Enums"]["task_status"] | null;
          note?: string | null;
          at?: string;
        };
        Update: {
          id?: string;
          task_id?: string;
          actor_id?: string | null;
          from_status?: Database["public"]["Enums"]["task_status"] | null;
          to_status?: Database["public"]["Enums"]["task_status"] | null;
          note?: string | null;
          at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          type: Database["public"]["Enums"]["task_type"];
          priority: Database["public"]["Enums"]["task_priority"];
          status: Database["public"]["Enums"]["task_status"];
          title: string;
          description: string | null;
          site_id: string | null;
          location: string | null;
          assigned_to: string | null;
          created_by: string | null;
          due_at: string | null;
          accepted_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          type?: Database["public"]["Enums"]["task_type"];
          priority?: Database["public"]["Enums"]["task_priority"];
          status?: Database["public"]["Enums"]["task_status"];
          title: string;
          description?: string | null;
          site_id?: string | null;
          location?: string | null;
          assigned_to?: string | null;
          created_by?: string | null;
          due_at?: string | null;
          accepted_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          type?: Database["public"]["Enums"]["task_type"];
          priority?: Database["public"]["Enums"]["task_priority"];
          status?: Database["public"]["Enums"]["task_status"];
          title?: string;
          description?: string | null;
          site_id?: string | null;
          location?: string | null;
          assigned_to?: string | null;
          created_by?: string | null;
          due_at?: string | null;
          accepted_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      team_members: {
        Row: {
          team_id: string;
          user_id: string;
          added_at: string;
        };
        Insert: {
          team_id: string;
          user_id: string;
          added_at?: string;
        };
        Update: {
          team_id?: string;
          user_id?: string;
          added_at?: string;
        };
      };
      teams: {
        Row: {
          id: string;
          name: string;
          supervisor_id: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          supervisor_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          supervisor_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      user_roles: {
        Row: {
          user_id: string;
          role: Database["public"]["Enums"]["app_role"];
          granted_by: string | null;
          granted_at: string;
        };
        Insert: {
          user_id: string;
          role: Database["public"]["Enums"]["app_role"];
          granted_by?: string | null;
          granted_at?: string;
        };
        Update: {
          user_id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          granted_by?: string | null;
          granted_at?: string;
        };
      };
      vehicles: {
        Row: {
          id: string;
          plate: string;
          label: string | null;
          type: string | null;
          status: Database["public"]["Enums"]["vehicle_status"];
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          plate: string;
          label?: string | null;
          type?: string | null;
          status?: Database["public"]["Enums"]["vehicle_status"];
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          plate?: string;
          label?: string | null;
          type?: string | null;
          status?: Database["public"]["Enums"]["vehicle_status"];
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      zones: {
        Row: {
          id: string;
          name: string;
          area: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          area?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          area?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
    };
    Views: { [key: string]: never };
    Functions: { [key: string]: never };
    Enums: {
      app_role: "super_admin" | "control_operator" | "dispatcher" | "supervisor" | "guard" | "patrol" | "technician";
      attendance_method: "gps_geofence" | "manual" | "qr" | "nfc";
      attendance_status: "pending" | "verified" | "rejected" | "flagged";
      checkpoint_method: "geofence" | "qr" | "nfc";
      employee_status: "active" | "suspended" | "inactive";
      employment_type: "guard" | "patrol" | "technician" | "office";
      geofence_event_source: "server" | "device";
      geofence_event_type: "enter" | "exit" | "dwell";
      geofence_shape: "polygon" | "circle";
      incident_status: "open" | "acknowledged" | "in_progress" | "resolved" | "false_alarm";
      incident_type: "sos" | "panic" | "alarm" | "medical" | "security" | "other";
      patrol_status: "in_progress" | "completed" | "abandoned";
      shift_status: "scheduled" | "active" | "completed" | "missed" | "cancelled";
      task_priority: "low" | "normal" | "high" | "critical";
      task_status: "open" | "assigned" | "accepted" | "in_progress" | "completed" | "cancelled";
      task_type: "patrol" | "inspection" | "maintenance" | "response" | "other";
      vehicle_status: "available" | "in_use" | "maintenance" | "retired";
    };
    CompositeTypes: { [key: string]: never };
  };
};


// Convenience helpers
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
